version: '3.9'

services:
  api:
    build:
      context: .
      dockerfile: MyApp.Api/Dockerfile
    container_name: myapp-api
    ports:
      - "8080:8080"
    env_file:
      - .env
    depends_on:
      - db
    networks:
      - myapp-network

  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: myapp-db
    environment:
      SA_PASSWORD: "StrongPassword123!"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - sql_data:/var/opt/mssql
    networks:
      - myapp-network

networks:
  myapp-network:

volumes:
  sql_data:
